-- Role: ryandayrit
-- DROP ROLE IF EXISTS ryandayrit;

CREATE ROLE ryandayrit WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:vwmZBbe71bjx9W0FtCbSPQ==$cOBmy1YkM4DPpuiTi0NAgp1rDjOFRvMpCZ0YNzSq/jk=:Axvt47N8Zy+zGzWghjTOtJq79MF2gStusBwihsvJMFE=';